### ISSUE TITLE
[BUG] Speed is missing from hud when entering a new stage. 

### ISSUE THREAD

**Issue by aKjeller** [olokos/Surftimer-olokos#5]
**Describe the bug**
When the hud is displaying time difference the speed goes blank. 

**Screenshots**
![bild](https://user-images.githubusercontent.com/44802724/79114516-c5be6b00-7d83-11ea-8120-6121d4b26527.png)

**Plugin List**
SurfTimer and z4lab mapchooser

**Additional context**
(An improvment would be if it displayed the prestrafe speed leaving the stage zone.

**Comment by sashajov** [comment]
I noticed there is a problem with the lower limit of the allowed characters in the center hud after this famous Valve's update. I fixed it by compressing color hex codes in misc.sp file.

E.g. #FFFFCC is same as #FFC

You can find short but similar or even same color hex code by using this web script: http://maettig.com/?page=PHP/CSS_Color_Converter

It's not enough because I was also forced to remove the u/s after the speed and also + and - before SR and PB to make enough space.

This is just fix for enabling speed, but I hope that developers will fix it aswell.

I will be happy if olokos fix it in his build because then I will not need to change these things each time.

**Comment by olokos** [comment]
Can anybody check if the pull request that I have mentioned above by covert has resolved this issue?
In that case we wouldn't have to make color codes any shorter.

**Comment by olokos** [comment]
Nope, #13 is irrelevant to this issue.
We've got to get rid of the text, please try the latest code and see how much we can actually keep, I'm crashing to bed now. 👼

**Comment by CustomStats** [comment]
#37 Did not seem fix the issue of speed disappearing when going through stages. This also seems to have brought back the issue where the spacing on the HUD messes up, but this was already noted in the PR. 
https://streamable.com/8ba2eo

**Comment by olokos** [comment]
I agree, the problem is still there, we should try some different approach.
Maybe we can try removing -/+ or at least u/s to just u.
Currently 25 hours since I last slept, so going to bed. :)

**Comment by qawery-just-sad** [comment]
u think that if we reaise the value of `#define MAX_HINT_SIZE 225` to something like 255 or 512 that might help?

**Comment by qawery-just-sad** [comment]
here is a look at `#define MAX_HIN_SIZE 255` [video](https://youtu.be/6c0LliXYWaA) going beyond 255 makes no difference

**Comment by sashajov** [comment]
@qawery-just-sad  Where it is defined, I can try right now.

**Comment by breakthegreat** [comment]
Maybe implementing a cvar allowing the cp time (+00.00.00 or -00.00.00) to be displayed only in chat could be a hot fix issue.(that way the timer will be kept as if it was a linear map, although we run through some stages.)?
Something like **ck_showcp_chat_only 1** or **0**. This will not resolve the issue if people want their time on the timer itself, but it could be resolving the issue temporarly. 

I don't know anything in sourcepawn, just a quick new look from someone running a server, you guys are doing a great job keep it going!

**Comment by sashajov** [comment]
@qawery-just-sad good question is also, is that a safe?! Look this commit: https://github.com/olokos/Surftimer-olokos/commit/966ef60ab60affe1874fac28814a1caf34f0340b

On my test server working well, or it just looks that working well. not sure xD

**Comment by 13ace37** [comment]
There are a lot of factors btw. 
- SR Time
- PB Time
- User side panel module order
- ...

**Comment by qawery-just-sad** [comment]
@sashajov setting max hint size to 255 is safe, why would it not be? it's just the buffer
yea i get that there might be more characters for those so... 
![image](https://user-images.githubusercontent.com/53490397/80143245-d0130d00-85ac-11ea-8279-10eff459cf06.png)

**Comment by qawery-just-sad** [comment]
btw do we need to have small font?
![image](https://user-images.githubusercontent.com/53490397/80149966-d2c72f80-85b7-11ea-8351-5a5fa22eba77.png)


that's the most i could get by introducing this
`PrintCSGOHUDText(client, "<br>%s\t%s\n%s\t%s\n%s\t%s", module[0], module[1], module[2], module[3], module[4], module[5]);` in line 3507

**Comment by 13ace37** [comment]
you could remove the `<br>` too i guess

**Comment by qawery-just-sad** [comment]
nah the `<br>` makes it nice to look at, but if we wanna save space yea that would have to go to the bin

**Comment by 13ace37** [comment]
wdym by
> makes it nice to look at

would look a lot better without the gap :)

**Comment by 13ace37** [comment]
dev branch with 
```cpp
PrintCSGOHUDText(client, "%s\t%s\n%s\t%s\n%s\t%s", module[0], module[1], module[2], module[3], module[4], module[5]);
```
![image](https://user-images.githubusercontent.com/29045525/80151513-79accb00-85ba-11ea-93f5-5df7e44f1abb.png)

**Comment by olokos** [comment]
Actually at this point it's still cutting off "u/s" after passing a stage, which is still a bit of an eyesore.

**Comment by qawery-just-sad** [comment]
remove  `class='fontSize-sm'` , yes it makes the letters bigger and yes that is still not a solution to the problem

**Comment by olokos** [comment]
I've noticed that removing "/s" from "u/s" helps nothing at all, so we're not running out of characters, but we're generating too much and getting cut off it seems.

@qawery-just-sad going to try that

**Comment by olokos** [comment]
@qawery-just-sad That totally did it!
Let's find some better way to resize this text then and we're golden!

**Comment by olokos** [comment]
![Photo of current state](https://image.prntscr.com/image/BGw_lcjKR4C_BIL2TVx5BQ.png)
That's how it looks like.

We're not missing any letter now, but the size is a lot bigger.
I tried with `<font size='10%;'>` but size remains the same.
same story with `<h1 size='10%;'>`.

Any ideas how to properly set text size with sourcepawn html?

**Comment by qawery-just-sad** [comment]
wish we could use csgo hardcoded values for colors and maybe skip the whole html
@olokos have you tried `<font-size=small>` ?

**Comment by olokos** [comment]
@qawery-just-sad not really, can you give it a shot, along with `font-size='10px'`?
I'll be going off for a bit.

**Comment by qawery-just-sad** [comment]
so i tried `<font-size='10px'>` and `<font-size=small>` as well as `<small>...</small>` and none of them made the hint text smaller

**Comment by sashajov** [comment]
Actually I really like that big timer xD

**Comment by qawery-just-sad** [comment]
i see ace is surfing with hud scale 0.95 (so is olokos)

**Comment by sashajov** [comment]
> i see ace is surfing with hud scale 0.95 (so is olokos)

Haha I forgot that I am on 0.7 xD

**Comment by qawery-just-sad** [comment]
yee 1440p and 0.95 kill me, 0.5 perfection

**Comment by olokos** [comment]
hud_scaling 0.85 to be exact, I don't even remember setting it in my config, but it undoubtedly is there! :D

**Comment by olokos** [comment]
But guys, please do build the dev branch and test it please, I think we might make a release just for this change and close this issue.
b702df4db5874069f9e758e244aedecd76cae0a8
But I think I will merge some recent pull requests before doing next release, some good stuff in them. <3
